#!/bin/bash
# Generate the site with landonhotel.py, then run a python.http server at localhost:8000
#
# Default port is 8000; a different port can be specified with the -p option.
#
# Root of server assumed to be 'output/'. Change with the -d option.
#
# Change url setting with -u option (see landonhotel.py)

usage() {
    echo "Usage: $0 [-p port] [-u urls] [-d root]" >&2
    exit 1
}

PORT=8000
URLS=""
ROOT="output"

while getopts ":p:u:d:" opt; do
    case $opt in
        p|P)
            PORT="$OPTARG"
            ;;
        u|U)
            URLS="$OPTARG"
            ;;
        d|D)
            ROOT="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            usage
            ;;
    esac
done

# If URLS is unset or empty string, ignore it
if [ -z "${URLS}" ]; then
    python landonhotel.py
else
    python landonhotel.py -u "$URLS"
fi

cd $ROOT
python -m http.server "$PORT"
